In [22]:
from osgeo import gdal, osr
import re
from typing import Union
import h5py
import numpy as np
import os

# Define Wavelengths and Full Width at Half Maximum (FWHM) for spectral bands
wavelengths = [444, 475, 531, 560, 650, 668, 705, 717, 740, 862]  # In nm
fwhm = [28, 32, 14, 27, 16, 14, 10, 12, 18, 57]

def create_h5_file_from_dict(data, h5_file, group_name="/"):
    """Recursively create groups and datasets in an HDF5 file from a dictionary."""
    for key, value in data.items():
        if isinstance(value, dict):
            subgroup_name = f"{group_name}/{key}"
            _ = h5_file.create_group(subgroup_name)
            create_h5_file_from_dict(value, h5_file, subgroup_name)
        else:
            dataset_name = f"{group_name}/{key}"
            if os.path.basename(group_name) == 'Coordinate_System':
                dataset = h5_file.create_dataset(dataset_name, data=str(value), dtype=h5py.string_dtype())
            else:
                dataset = h5_file.create_dataset(dataset_name, data=value)
            if key in ['Wavelength', 'FWHM']:
                dataset.attrs['Units'] = 'nanometers'

def remove_non_numeric(input_string):
    """Remove non-numeric characters from a string."""
    return re.sub(r'\D', '', input_string)

def load_data(data: Union[str, np.array], expected_shape):
    """Loads data from file or ensures an array has the expected shape."""
    if isinstance(data, str):
        data_array = gdal.Open(data).ReadAsArray()
    else:
        data_array = np.array(data)
    
    if data_array.shape != expected_shape:
        raise ValueError(f"Data shape mismatch: Expected {expected_shape}, but got {data_array.shape}")
    
    return data_array

def tiff_to_h5(reflectance_tiff_path: str, slope_data: Union[str, np.array],
               aspect_data: Union[str, np.array], path_length_data: Union[str, np.array],
               solar_zenith_data: Union[str, np.array], solar_azimuth_data: Union[str, np.array]):
    """Converts a TIFF reflectance file into an HDF5 format with metadata and ancillary data."""

    # Open reflectance TIFF
    reflectance_ds = gdal.Open(reflectance_tiff_path)
    reflectance_data = reflectance_ds.ReadAsArray()[:10, :, :]  # Use first 10 bands
    img_shape = reflectance_data.shape[1:]  # (rows, cols)

    # Load ancillary data
    slope_data = load_data(slope_data, img_shape)
    aspect_data = load_data(aspect_data, img_shape)
    path_length_data = load_data(path_length_data, img_shape)
    solar_zenith_data = load_data(solar_zenith_data, img_shape)
    solar_azimuth_data = load_data(solar_azimuth_data, img_shape)

    # Set sensor angles to zero matrices matching image shape
    sensor_zenith_data = np.zeros(img_shape)
    sensor_azimuth_data = np.zeros(img_shape)

    # Extract spatial metadata
    proj = reflectance_ds.GetProjection()
    geo_transform = reflectance_ds.GetGeoTransform()
    
    spatial_ref = osr.SpatialReference()
    spatial_ref.ImportFromWkt(proj)
    epsg_code = spatial_ref.GetAuthorityCode(None)

    utm_zone = int(remove_non_numeric(proj.split("UTM zone ")[1].split(",")[0])) if "UTM zone" in proj else None
    map_info_string = f"UTM, 1.000, 1.000, {geo_transform[0]:.3f}, {geo_transform[3]:.3f}, {geo_transform[1]:.3f}, {geo_transform[5]:.3f}, {utm_zone}, North, WGS-84, units=Meters, 0"

    # HDF5 Structure
    h5_data = {
        'NIWO': {
            'Reflectance': {
                'Metadata': {
                    'Coordinate_System': {
                        'Coordinate_System_String': proj,
                        'EPSG Code': epsg_code,
                        'Map_Info': map_info_string,
                        'Proj4': spatial_ref.ExportToProj4()
                    },
                    "Ancillary_Imagery": {
                        "Path_Length": path_length_data,  # Now uses raster-based path length
                        "Slope": slope_data,
                        "Aspect": aspect_data
                    },
                    "Logs": {
                        "Solar_Azimuth_Angle": solar_azimuth_data,
                        "Solar_Zenith_Angle": solar_zenith_data
                    },
                    "to-sensor_Azimuth_Angle": sensor_azimuth_data,
                    "to-sensor_Zenith_Angle": sensor_zenith_data,
                    "Spectral_Data": {
                        'FWHM': fwhm,
                        'Wavelength': wavelengths
                    }
                },
                'Reflectance_Data': np.transpose(reflectance_data, axes=(1, 2, 0))  # Convert to (rows, cols, bands)
            }
        }
    }

    # Save to HDF5
    h5_filename = 'NEON_D13_NIWO_test' + os.path.basename(reflectance_tiff_path).replace('.tif', '.h5')
    with h5py.File(h5_filename, "w") as hdf_file:
        create_h5_file_from_dict(h5_data, hdf_file)

    print(f"HDF5 file created: {h5_filename}")


In [28]:
import ephem
import rasterio
import numpy as np
from rasterio import Affine as A
from rasterio.warp import reproject, Resampling
import h5py
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# from osgeo import gdal
import seaborn as sns
import rasterio
from pyproj import Proj, transform
from rasterio.transform import from_origin
import ephem
import datetime
import math
import warnings

def pixel_to_coord(file_path):
     with rasterio.open(file_path) as src:
            band1 = src.read(1)
            print('Band1 has shape', band1.shape)
            height = band1.shape[0]
            width = band1.shape[1]
            cols, rows = np.meshgrid(np.arange(width), np.arange(height))
            xs, ys = rasterio.transform.xy(src.transform, rows, cols)
            eastings= np.array(xs)
            northings = np.array(ys)
            print('eastings shape', eastings.shape)
            p1 = Proj(src.crs)
            p2 = Proj(proj='latlong', datum='WGS84')
            lons, lats = transform(p1, p2, eastings, northings)
     return lons, lats, cols, rows,


file_path = file_path #r'/home/jovyan/data-store/cross-sensor-cal/data_set2/aligned_orthomosaic.tif'
longitudes, latitudes, cols, rows = pixel_to_coord(file_path)

# # # Function to convert lat/lon to row/col
# # def latlon_to_rowcol(transform, lat, lon):
# #     col, row = ~transform * (lon, lat)
# #     return int(row), int(col)

# Convert the date and time to UTC. The time given is 2:34 PM, which is 14:34 in 24-hour format
date_time_str = '2023-08-01 21:34:00'


with rasterio.open(file_path) as src:
    # Get the affine transform for the raster
    transform = src.transform
    
    # Create arrays to hold the azimuth and zenith values
    azimuth = np.zeros((src.height, src.width), dtype=np.float32)
    zenith = np.zeros((src.height, src.width), dtype=np.float32)
    
    # Assume a date and time for the Sun position calculation
    observer = ephem.Observer()
    observer.date = ephem.date(date_time_str)
    
    # Iterate over each pixel in the raster
    for row in range(latitudes.shape[0]):
        for col in range(latitudes.shape[1]):
            #lon, lat = pixel_to_coord(transform, row, col)
            observer.lat, observer.lon = latitudes[row,col], longitudes[row,col]
            
            sun = ephem.Sun(observer)
            
            # Convert azimuth and altitude (zenith angle is 90 - altitude) to degrees
            az = np.degrees(sun.az)
            #az = sun.az
            alt = np.degrees(sun.alt)
            zen = 90 - sun.alt
            
            azimuth[row, col] = az
            zenith[row, col] = zen



# with rasterio.open(file_path) as src:
#     # Get the affine transform for the raster
#     transform = src.transform
    
#     # Create arrays to hold the azimuth and zenith values
#     azimuth = np.zeros((src.height, src.width), dtype=np.float32)
#     zenith = np.zeros((src.height, src.width), dtype=np.float32)
    
#     # Assume a date and time for the Sun position calculation
#     observer = ephem.Observer()
#     observer.date = ephem.date(date_time_str)
    
#     # Iterate over each pixel in the raster
#     for row in range(src.height):
#         for col in range(src.width):
#             #lon, lat = pixel_to_coord(transform, row, col)
#             observer.lat, observer.lon = str(lat), str(lon)
            
#             sun = ephem.Sun(observer)
            
#             # Convert azimuth and altitude (zenith angle is 90 - altitude) to degrees
#             az = np.degrees(sun.az)
#             alt = np.degrees(sun.alt)
#             zen = 90 - alt
            
#             azimuth[row, col] = az
#             zenith[row, col] = zen

Band1 has shape (1018, 672)
eastings shape (1018, 672)


/tmp/ipykernel_765/2800905525.py:33: FutureWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  lons, lats = transform(p1, p2, eastings, northings)


In [29]:
longitudes

array([[-105.54106897, -105.54106604, -105.5410631 , ..., -105.53910866,
        -105.53910573, -105.5391028 ],
       [-105.54106895, -105.54106602, -105.54106309, ..., -105.53910864,
        -105.53910571, -105.53910278],
       [-105.54106893, -105.541066  , -105.54106307, ..., -105.53910862,
        -105.53910569, -105.53910276],
       ...,
       [-105.5410509 , -105.54104797, -105.54104504, ..., -105.53909066,
        -105.53908773, -105.5390848 ],
       [-105.54105088, -105.54104795, -105.54104502, ..., -105.53909064,
        -105.53908771, -105.53908478],
       [-105.54105086, -105.54104793, -105.541045  , ..., -105.53909062,
        -105.53908769, -105.53908476]])

In [30]:
latitudes

array([[40.03632017, 40.03632018, 40.0363202 , ..., 40.03632931,
        40.03632932, 40.03632934],
       [40.03631792, 40.03631793, 40.03631795, ..., 40.03632706,
        40.03632707, 40.03632708],
       [40.03631567, 40.03631568, 40.03631569, ..., 40.0363248 ,
        40.03632482, 40.03632483],
       ...,
       [40.03403405, 40.03403406, 40.03403408, ..., 40.03404319,
        40.0340432 , 40.03404321],
       [40.0340318 , 40.03403181, 40.03403182, ..., 40.03404093,
        40.03404095, 40.03404096],
       [40.03402955, 40.03402956, 40.03402957, ..., 40.03403868,
        40.0340387 , 40.03403871]])

In [31]:
azimuth

array([[34.854084, 34.85425 , 34.854416, ..., 34.966404, 34.966568,
        34.966736],
       [34.854084, 34.85425 , 34.854416, ..., 34.966404, 34.966568,
        34.966736],
       [34.854084, 34.85425 , 34.854416, ..., 34.966404, 34.96657 ,
        34.96674 ],
       ...,
       [34.855114, 34.85528 , 34.85545 , ..., 34.96743 , 34.967598,
        34.96777 ],
       [34.855114, 34.85528 , 34.855453, ..., 34.96743 , 34.9676  ,
        34.96777 ],
       [34.855118, 34.855286, 34.855453, ..., 34.967434, 34.9676  ,
        34.96777 ]], dtype=float32)

In [32]:
zenith

array([[89.13177 , 89.13177 , 89.13177 , ..., 89.132904, 89.132904,
        89.132904],
       [89.13177 , 89.13177 , 89.13177 , ..., 89.132904, 89.132904,
        89.132904],
       [89.13177 , 89.13177 , 89.13177 , ..., 89.132904, 89.132904,
        89.13291 ],
       ...,
       [89.13301 , 89.13301 , 89.13301 , ..., 89.13415 , 89.13415 ,
        89.13415 ],
       [89.13301 , 89.13301 , 89.13302 , ..., 89.13415 , 89.13415 ,
        89.13415 ],
       [89.13301 , 89.13302 , 89.13302 , ..., 89.13415 , 89.13415 ,
        89.134155]], dtype=float32)

In [19]:
np.mean(latitudes)

40.03517944314455

In [20]:
np.mean(longitudes)

-105.54007684654168

In [34]:
tiff_to_h5('/home/jovyan/data-store/cross-sensor-cal/data_set2/aligned_orthomosaic.tif', '/home/jovyan/data-store/cross-sensor-cal/data_set2/slope_smooth_slope.tif', '/home/jovyan/data-store/cross-sensor-cal/data_set2/aspect_smooth_aspect.tif', '/home/jovyan/data-store/cross-sensor-cal/data_set2/chm_AOP-MRS2-08-14-23.tif', zenith, azimuth)
print("6")

HDF5 file created: NEON_D13_NIWO_testaligned_orthomosaic.h5
6


In [88]:
azimuth

array([[5.0587783, 5.058781 , 5.0587845, ..., 5.0607386, 5.060742 ,
        5.060745 ],
       [5.0587783, 5.0587816, 5.0587845, ..., 5.0607386, 5.060742 ,
        5.060745 ],
       [5.0587783, 5.0587816, 5.0587845, ..., 5.060739 , 5.060742 ,
        5.060745 ],
       ...,
       [5.0587964, 5.0587997, 5.0588026, ..., 5.0607567, 5.0607595,
        5.060763 ],
       [5.0587964, 5.0587997, 5.0588026, ..., 5.0607567, 5.06076  ,
        5.060763 ],
       [5.0587964, 5.0587997, 5.0588026, ..., 5.0607567, 5.06076  ,
        5.060763 ]], dtype=float32)

In [77]:
from math import sin, cos, radians, degrees, acos, asin

# Input parameters
latitude = 40.03505796360895  # degrees
longitude = -105.53999928775333  # degrees
day_of_year = 226  # example: June 21
local_time = 14.24  # noon in hours
timezone_offset = -7  # UTC offset for PDT

# Solar declination
declination = -23.44 * cos(radians(360 * (day_of_year + 10) / 365))

# Equation of Time (EoT)
eot = 7.5 * sin(radians(360 * (day_of_year - 81) / 365))

# Local Solar Time (LST)
lst = local_time + (longitude / 15) + eot - timezone_offset

# Hour Angle (H)
hour_angle = 15 * (lst - 12)

# Solar Zenith Angle
cos_zenith = (sin(radians(latitude)) * sin(radians(declination)) +
              cos(radians(latitude)) * cos(radians(declination)) * cos(radians(hour_angle)))
zenith = degrees(acos(cos_zenith))

# Solar Azimuth Angle
cos_azimuth = (sin(radians(declination)) - sin(radians(latitude)) * cos(radians(zenith))) / \
              (cos(radians(latitude)) * sin(radians(zenith)))
azimuth = degrees(acos(cos_azimuth))

# Adjust azimuth depending on hour angle
if hour_angle > 0:
    azimuth = 360 - azimuth

print(f"Solar Zenith Angle: {zenith:.2f}°")
print(f"Solar Azimuth Angle: {azimuth:.2f}°")


Solar Zenith Angle: 88.90°
Solar Azimuth Angle: 287.69°


In [76]:
zenith


88.89764248672688

In [ ]:
NEON_D13_NIWO_ortho_mrs2.h5